---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - eirenyx.eirenyx
  resources:
  - policies
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eirenyx.eirenyx
  resources:
  - policies/finalizers
  - tools/finalizers
  verbs:
  - update
- apiGroups:
  - eirenyx.eirenyx
  resources:
  - policies/status
  - tools/status
  verbs:
  - get
  - patch
  - update
