apiVersion: eirenyx.eirenyx/v1alpha1
kind: Policy
metadata:
  labels:
    app.kubernetes.io/name: eirenyx
    app.kubernetes.io/managed-by: kustomize
  name: policy-sample
spec:
  # TODO(user): Add fields here
