apiVersion: eirenyx.eirenyx/v1alpha1
kind: Tool
metadata:
  labels:
    app.kubernetes.io/name: eirenyx
    app.kubernetes.io/managed-by: kustomize
  name: litmus
spec:
  type: litmus
  enabled: true
  namespace: litmus
  values:
    mongodb:
      image:
        registry: dlavrenuek
        repository: bitnami-mongodb-arm
        tag: "6.0.13"
        