apiVersion: eirenyx.eirenyx/v1alpha1
kind: Policy
metadata:
  name: falco-package-manager
spec:
  type: falco
  enabled: true
  falco:
    rules:
      - name: Package manager executed in container
        condition: >
          spawned_process and container and
          proc.name in (apt, apt-get, yum, dnf, apk)
        output: >
          Package manager executed inside container
          (proc=%proc.name container=%container.name user=%user.name)
        priority: WARNING
        tags:
          - container
          - persistence
